### ISSUE TITLE
Thumbnail image resizing for collection items

### ISSUE THREAD

**Issue by CourtneyMcClellan** [adamjarling/loc-speculative-annotations#101]
Resizing for thumbnail images for viewing/selection of collection items. Courtney and @jaimemears will upload and share folder

**Comment by CourtneyMcClellan** [comment]
thumbnails found here: https://drive.google.com/drive/folders/18HCarxf-18YbQHUvKuGKF69l5kjbft3c?usp=sharing

**Comment by adamjarling** [comment]
@CourtneyMcClellan Just quickly previewing these, a few things:

- All thumbnails should be saved/exported for web quality.  Ideally jpg files, 72dpi.  They should weigh in file-size around 100-300kb max.
- It looks like the dimensions are still different for the few I've downloaded.  In order to get a uniform, grid-like display as we discussed earlier, each thumbnail image should be the exact same dimensions.  For example, 800x800px.  Or 640x480px.  Whatever you want, but they should be consistent or we're in the same boat.

**Comment by CourtneyMcClellan** [comment]
A few updates/questions:

- Everything I saved were 72 dpi. Right now I am going to go through and
make the files jpg and see if that decreases the weight.
- Yes, my hope was that we would not crop of alter the shape of the item,
but instead, by using 780 pixels as our limit, they would be closer to the
same size. Do you see any issues with this plan?

Additionally, I have set the items at 72 dpi but when Jaime opens them, she is seeing they are at 96 dpi-- we don't know why. If you see this discrepancy, let us know.

**Comment by CourtneyMcClellan** [comment]
Images have been reformatted: https://drive.google.com/drive/folders/18HCarxf-18YbQHUvKuGKF69l5kjbft3c?usp=sharing

**Comment by adamjarling** [comment]
Thumbnail Images now uploaded and in place.  Closing.

**Comment by jaimemears** [comment]
Give Muybridge item navy background so that it is visible
Whitman (item 37) thumbnail has a lot of white space- Courtney crop
Selfie thumbnail (item 7) pulls up temperance map- replace with temperance map thumbnail
2 Clara Barton (item 33, item 34- opens)
Mural Painting (item 12) there is text and no thumbnail, but the item itself shows on the canvas

**Comment by CourtneyMcClellan** [comment]
- Images updated, old deleted: Muybridge image Item 1 (00650866_thumbnail)
Whitman Item 37 (mss454430217_thumbnail)

- Added thumbnail for item 7- currently wrong image, replace with: Temperance (2004633094_thumbnail)

- Item 34 (master-pnp-ppmsca-02900-02935u_thumbnail (1)) needs to be deleted. It is a duplicate, item master is duplicate as well, will note in the associated ticket.

- Add mural Item 12 (2011631432_thumbnail) currently is just showing as text
<img width="400" alt="Screen Shot 2021-05-13 at 1 55 54 PM" src="https://user-images.githubusercontent.com/77364108/118166016-f9d6e600-b3f2-11eb-9a03-8d0292fda704.png">


All items were uploaded here in case batch loading is easier than individual 
https://drive.google.com/file/d/1_ZXz044GWZii7zv0Qx-5A_tdDXNSfYQS/view?usp=sharing

**Comment by adamjarling** [comment]
Latest images now updated and pushing to staging.

![image](https://user-images.githubusercontent.com/3020266/118652955-b393d500-b7ac-11eb-8ea8-5a297ac2be95.png)
