### ISSUE TITLE
Default color and font for text tool

### ISSUE THREAD

**Issue by jaimemears** [adamjarling/loc-speculative-annotations#110]
Default setting so people can select text tool and just run with it. @jessvu could you suggest a color and font and then assign the ticket to @CourtneyMcClellan to review?

**Comment by jessvu** [comment]
![image](https://user-images.githubusercontent.com/32075716/117594237-b0914880-b10b-11eb-80db-f3fcecf04479.png)
this is the current order of the text options and color options so my suggestion would be to set Reenie Beenie as the font and the color green as the default selections since they come first. However, if we want a different pairing, I suggest reorganizing the order in which they appear so that the first options listed are what is pre-selected for the user. @CourtneyMcClellan

**Comment by CourtneyMcClellan** [comment]
This works for me

**Comment by jaimemears** [comment]
development entering final sprint - closing this ticket as not a priority for mvp.
