### ISSUE TITLE
Default LC Staff Annotation

### ISSUE THREAD

**Issue by jaimemears** [adamjarling/loc-speculative-annotations#119]
For items that dont have staff annotations, a default annotation will need to be created. Could be just text that says "not available"? Can we make it playful somehow?

**Comment by adamjarling** [comment]
Currently if no Curator annotation exists (stored in the IIIF manifest), then this checkbox will not appear.  If you want to create a default annotation, just share it in a comment in this issue.   The default annotation should be created via the app, as tested via this process described here:  https://github.com/adamjarling/loc-speculative-annotations/issues/98

![image](https://user-images.githubusercontent.com/3020266/117806199-98125280-b21f-11eb-8aff-bdad4568e3e9.png)

**Comment by jaimemears** [comment]
There may be the ability to just not show the LC Staff Annotation option for items where it is not available. Lets review Jess vu's mock up and discuss what is easier for @adamjarling - turn the box off and on based on the item, or load annotations for all items- some will be "default" annotations.

**Comment by adamjarling** [comment]
@jaimemears It's already wired up to not show the LC Staff Annotation checkbox & label, if no Staff annotation exists in the IIIF manifest.  This is in line w/ @jessvu 's mockups, and since it's the current behavior, would be easiest to run with.  

![image](https://user-images.githubusercontent.com/3020266/118264473-5bdc2d80-b47d-11eb-87b6-55678b31e3d9.png)

**Comment by jaimemears** [comment]
This issue is no longer relevant. If an item does not have a staff annotation then the option will not appear.
