### ISSUE TITLE
Static Canvas

### ISSUE THREAD

**Issue by jessvu** [adamjarling/loc-speculative-annotations#33]
![image](https://user-images.githubusercontent.com/32075716/106690363-a78a5b80-659f-11eb-880a-12dc5a8bfbd3.png)

https://docs.google.com/presentation/d/1GPby059FlA5RSSo-xBiE1HTkOOstBC17VkPuwfrTWzA/edit#slide=id.gb5e38bc965_0_9

I'm wondering if on OSD you could zoom the image out a little bit so that there's padding above and below the image and make the entire canvas area (including the image) static for the LOC staff user testing. I'm imagining this to be the default view of the canvas at the most zoomed out state upon entry of the application. 

I would still like for the zooming in/out functionality to work, but when the canvas is zoomed out all the way and the whole image can be seen, if we could disable the ability to move it, I think it would solve for the concerns we have about jumpiness. I understand if this is another limitation of OSD, just wanted to share my idea in case it's doable task.

**Comment by adamjarling** [comment]
@jessvu So I have this now working where the image and canvas will render zoomed out 100%, and are static.  

OSD offers a configuration option `visibilityRatio` (https://openseadragon.github.io/docs/OpenSeadragon.html#.Options) which essentially tells OSD how much of the image needs to stay inside the bounds of OSD's canvas.  By default the value is 0.5, allowing a user to pan to the greatest level, only see half the image in the OSD canvas.

I updated this setting to 1, which tells OSD to keep the entire image constrained within the canvas. Along with some other default zoom settings, I was able to get the image to display with some perceived margins around all edges of the image. 

However, because we're looking at this from a laptop viewport (I assume....desktop may be different), the viewport is wider than tall, and there are no issues showing extra horizontal padding until a very zoomed-in level.  This means that horizontal padding is disabled, until a zoom level is reached where the image zoom level is wider than current canvas.   Maybe this is fine...to me it seems a little odd that I can pan vertically but not horizontally until a certain point, but my bias is I'm used to looking at deep zoom image viewers more than the average person.  

So...I'll push up the changes and let me know yea/nea? 

![image](https://user-images.githubusercontent.com/3020266/107854133-8c112300-6ddf-11eb-8a25-888f7319cdd4.png)

**Comment by adamjarling** [comment]
Actually still working on this. I'll ping you when it's pushed live @jessvu

**Comment by adamjarling** [comment]
Ok, just pushed the changes.

**Comment by adamjarling** [comment]
Just noticed the original size of the image on the canvas (for tall items), doesn't have top/bottom margin.  Need to figure out a better way to display the initial image size with margins all around, and (I think) set a dynamic minimum Zoom level in OpenSeadragon each time a new image is loaded into the Viewer.

**Comment by jaimemears** [comment]
The top/bottom margin has not been implemented, correct? (Doing backlog cleanup)

**Comment by adamjarling** [comment]
Correct, not yet implemented.  Since we're limiting how a user can move a Work around the OpenSeadragon viewer, I was running into problems getting the initial top margins consistent, per Work.  I'll revisit this.

**Comment by jaimemears** [comment]
@adamjarling I noticed with the return to a more "moveable" item in open sea dragon the margins have gone away. Is this an either/or situation? Meaning you cant have top and bottom margins and a moveable item simultaneously?

**Comment by jaimemears** [comment]
@adamjarling nvm! the items look centered in this newest push. Closing this ticket.
