### ISSUE TITLE
Match Cursors to Action Being Performed

### ISSUE THREAD

**Issue by jessvu** [adamjarling/loc-speculative-annotations#38]
![image](https://user-images.githubusercontent.com/32075716/107289827-99bb5700-6a33-11eb-9415-ea63287499a8.png)

<https://docs.google.com/presentation/d/1kOKl3iC7_b7VOVp64xXCJtnPoAcv90rll2J5jpHoA5s/edit#slide=id.gbc2a418f24_1_28>

**Comment by adamjarling** [comment]
So I think I have the cursors all in sync when switching between tools.  

For the Paint cursor, since there is no default browser brush cursor style, we'll need to go custom.  I can't seem to take a screen shot that grabs my cursor, but I have one version working now where the cursor becomes a SVG generated circle, roughly the same size and color as the brush the user has selected.  

At least this might push the ball forward a little into how we can refine the customization.

**Comment by adamjarling** [comment]
For the Drawing tool, Fabric lets us define a custom cursor.  Example implementation here.

https://codepen.io/curtisj44/pen/yGxJNX

**Comment by jessvu** [comment]
@adamjarling I think that the circle cursors matching the stroke size is great! Very happy with how that looks and is working
