### ISSUE TITLE
Change out Images

### ISSUE THREAD

**Issue by CourtneyMcClellan** [adamjarling/loc-speculative-annotations#43]
I want to change out the images we are using. I have attached 5 that I would like to add. @jaimemears will supply metadata. 

![Yellowstone](https://user-images.githubusercontent.com/77364108/109029348-c062ca00-7690-11eb-8cbc-ee8305f049ec.jpg)
![Whitman 1](https://user-images.githubusercontent.com/77364108/109029357-c3f65100-7690-11eb-8980-a97a32ddec30.jpg)
![Whitman 2](https://user-images.githubusercontent.com/77364108/109029363-c5277e00-7690-11eb-9fdb-6a80d65d2663.jpg)
![Costume 1](https://user-images.githubusercontent.com/77364108/109029444-d83a4e00-7690-11eb-92b4-e24591a2e848.jpg)
![Hurston 1](https://user-images.githubusercontent.com/77364108/109029529-eee0a500-7690-11eb-882a-98dc1ad8e3ff.jpg)

![Ice Cream](https://user-images.githubusercontent.com/77364108/109029620-06b82900-7691-11eb-84ee-5a36da5ce009.jpg)

**Comment by adamjarling** [comment]
@CourtneyMcClellan Great images.  I'll make the updates tonight after work.

**Comment by adamjarling** [comment]
@CourtneyMcClellan So there's actually 6 images here.  The Walt Whitman papers images are 2 separate images, which matters in how we're doing the Curator overlays.  

If you want to use both images together, we'll need to stitch them together either locally in a new, single JPG, or we can make the OpenSeadragon viewer render both together.

I'd prefer the first option, as we'll need a new primary image we deliver back to LOC for their curators to Annotate, which we then pull back into the application.  Otherwise, if it's not 100% exact, it may be jumpy switching Curator annotations on/off.

I don't suppose there's a file of these images combined into a single image that LOC already has prepped?

**Comment by adamjarling** [comment]
@CourtneyMcClellan For now I created a new combo image in Photoshop for the Walt Whitman notes.   I think this will work (or something like it...).

![walt-whitman-papers](https://user-images.githubusercontent.com/3020266/109164697-56a1f900-7740-11eb-96bf-40975751ccf0.jpg)

**Comment by CourtneyMcClellan** [comment]
Hey Adam,

Sorry for the delay I had to handle a few things today. Thank you for
moving forward. This is a good thing to test as we may have a couple
multi-image items to include. When you decide on the best format, we will
be sure to share them with you that way to make it easier.

Thanks,
Courtney

**Comment by adamjarling** [comment]
@CourtneyMcClellan  No problem!  For multi image items, the primary question is do you want the images displayed together or separately?  It'd be easiest to sync a User's annotations on top of a single image (which may be 2 images combined, as in the Walt Whitman example above).  

If this is an acceptable solution for you, I'd say we run with this approach.  You (or Olivia or whoever) could either prep the images in Photoshop, or I can do it as well.  They just need to be as large as possible to enable zooming and hi-resolution.

This also assumes that @jaimemears and LOC is ok with one of us manipulating the images like this?

The primary consideration I'm thinking through for this scenario, is how to toggle Curator's annotations for multi-image works and make it as simple a solution as possible.

**Comment by jaimemears** [comment]
I will take a look at this approach, but in theory I think its fine to manipulate pages so that they fit together (like an open book is what I’m imagining...)

Sent from my iPad

On Feb 26, 2021, at 7:32 AM, Adam J. Arling <notifications@github.com> wrote:

﻿

@CourtneyMcClellan<https://github.com/CourtneyMcClellan> No problem! For multi image items, the primary question is do you want the images displayed together or separately? It'd be easiest to sync a User's annotations on top of a single image (which may be 2 images combined, as in the Walt Whitman example above).

If this is an acceptable solution for you, I'd say we run with this approach. You (or Olivia or whoever) could either prep the images in Photoshop, or I can do it as well. They just need to be as large as possible to enable zooming and hi-resolution.

This also assumes that @jaimemears<https://github.com/jaimemears> and LOC is ok with one of us manipulating the images like this?

The primary consideration I'm thinking through for this scenario, is how to toggle Curator's annotations for multi-image works and make it as simple a solution as possible.

**Comment by adamjarling** [comment]
@CourtneyMcClellan @jaimemears For the "National Park" image, is it possible to find a hi-res version anywhere in LOC's archives?  The one I pulled from the image server is fairly lo-res compared to the others.  If it's not a big deal that's fine, just noticed it when going through the images, and it may affect zoom levels in the Viewer.

**Comment by CourtneyMcClellan** [comment]
This is the largest file I can find on the free to use site. If we still
need it to be larger, Jaime, do we have any options?
 National Parks.tif
<https://drive.google.com/file/d/1QxI38tJJSq7tkVjvhOj9Mx6XcafUr0nX/view?usp=drive_web>

**Comment by adamjarling** [comment]
@CourtneyMcClellan Ah, I didn't see that TIF file.  That file is perfectly huge, and I'll convert it to a JPG (browsers won't render TIF files) that's plenty hi-res.  Nice find.

**Comment by adamjarling** [comment]
Closing for now as new local files are added.  @jaimemears These are not being hosted via LOC's IIIF Image server.... based on today's IIIF meeting, if we want to support this, will need to re-visit in the future.

**Comment by jaimemears** [comment]
Noted. Thanks!
