### ISSUE TITLE
Padding Around Shapes Tool

### ISSUE THREAD

**Issue by jessvu** [adamjarling/loc-speculative-annotations#44]
**_NOT_** urgent
![image](https://user-images.githubusercontent.com/32075716/109569459-7b86cb00-7ab6-11eb-963d-8e749e573483.png)

**Comment by adamjarling** [comment]
@jessvu The Options Panel now uses the same button size as the primary Toolbar.  Differences in sizes now are due to the size of the icons themselves, pulled from the React Icons library.  

![image](https://user-images.githubusercontent.com/3020266/110121394-f0425980-7d83-11eb-861f-c62736db5fe6.png)

At any point if you or @CourtneyMcClellan want to update the icon selections, feel free.  I picked ones quickly a while ago without much thought...

https://react-icons.github.io/react-icons

**Comment by adamjarling** [comment]
Completed and closing.
