### ISSUE TITLE
item level hashtags

### ISSUE THREAD

**Issue by jaimemears** [adamjarling/loc-speculative-annotations#54]
Create unique hashtags for each item. these should appear in the sharing menu.

**Comment by CourtneyMcClellan** [comment]
@jaimemears since we have not selected the final 30ish items we can't name the specific item hashtags. However, what I am guessing this is asking is how we might format the hashtags overall? I am going to put these possibilities here for now: https://docs.google.com/document/d/1zfvqcWVt91GwO-mXvJ7bK8jTKcFLmKL3mjc6Kc1NPzI/edit

**Comment by jaimemears** [comment]
Yep, exactly. Just added a comment that the hashtags will need to be approved. Im happy to ask preliminarily about the format with our office of communications.

**Comment by CourtneyMcClellan** [comment]
@jaimemears will check with Comms and other relevant LC teams about hashtag approval

**Comment by jaimemears** [comment]
we have decided not to do this. i am closing this ticket.
